require "parallel"
require "etc"
require "open3"

module ImmosquareCleaner
  ##============================================================##
  ## Cleans every source file of a repository in one run, whatever
  ## its stack (Rails app, gem, Rust/Tauri app, JS package...).
  ##
  ## Files come from `git ls-files` (tracked + untracked, minus
  ## .gitignore), so each stack's build output (target/, dist/,
  ## app/assets/builds...) is skipped by the repository's own
  ## rules. Outside a git repository, every file under the root
  ## is listed and EXCLUDED_DIRS does the filtering.
  ##
  ## Only files with a dedicated processor or a Prettier-supported
  ## extension are cleaned: the Prettier fallback of the
  ## single-file clean would otherwise run on LICENSE, .env...
  ##
  ## Parallelized via threads (linters shell out, so the GVL is
  ## released). Override with: CLEANER_THREADS=N
  ##============================================================##
  class DirectoryCleaner

    ##============================================================##
    ## EXCLUDED_DIRS  : folder names skipped at any depth
    ## EXCLUDED_PATHS : paths relative to the root — generated or
    ##                  vendored content that repositories commit
    ##                  (db/schema.rb, Tauri schemas...) and test
    ##                  fixtures that must stay as written
    ##============================================================##
    EXCLUDED_DIRS = [
      ".git",
      "build",
      "coverage",
      "dist",
      "log",
      "node_modules",
      "target",
      "testdata",
      "tmp",
      "vendor"
    ].freeze
    EXCLUDED_PATHS = [
      "app/assets/builds",
      "app/assets/fonts",
      "app/assets/images",
      "db",
      "public",
      "src-tauri/gen",
      "src-tauri/permissions/autogenerated",
      "test"
    ].freeze
    EXCLUDED_FILES = [
      "npm-shrinkwrap.json",
      "package-lock.json",
      "pnpm-lock.yaml"
    ].freeze
    EXCLUDED_SUFFIXES = [
      ".min.css",
      ".min.js"
    ].freeze

    def self.run(root)
      new(root).run
    end

    attr_reader :root

    ##============================================================##
    ## Everything under `generators/**/templates/` is raw template
    ## content, usually ERB behind the target file's extension: any
    ## formatter would mangle its tags. Shared with
    ## ImmosquareCleaner.clean so a single-file clean skips it too
    ##============================================================##
    def self.generator_template?(folders)
      generators = folders.index("generators")
      !generators.nil? && folders.drop(generators + 1).include?("templates")
    end

    def initialize(root)
      @root = File.expand_path(root)
    end

    def run
      paths   = file_paths
      total   = paths.size
      mutex   = Mutex.new
      index   = 0
      threads = ENV["CLEANER_THREADS"]&.to_i || [Etc.nprocessors, 8].min
      started = Process.clock_gettime(Process::CLOCK_MONOTONIC)

      puts("Cleaning #{total} files in #{root} with #{threads} threads...")

      Parallel.each(paths, :in_threads => threads) do |file_path|
        i = mutex.synchronize { index += 1 }
        puts("#{i}/#{total} - #{file_path}")
        ImmosquareCleaner.clean(file_path)
      end

      elapsed = Process.clock_gettime(Process::CLOCK_MONOTONIC) - started
      mins    = (elapsed / 60).to_i
      secs    = (elapsed % 60).round(1)
      puts("Done in #{mins}m #{secs}s (#{total} files, #{threads} threads)")
    end

    def file_paths
      listed_files(root).sort
    end

    private

    ##============================================================##
    ## Paths are relative to `dir`, so EXCLUDED_PATHS applies from
    ## each repository's own root. git lists a nested repository
    ## (`gem/`) or a submodule as a single directory entry without
    ## descending into it: it is walked with its own git listing,
    ## otherwise a parent folder of repositories cleans nothing
    ##============================================================##
    def listed_files(dir)
      relative_paths(dir).flat_map do |entry|
        path          = entry.delete_suffix("/")
        absolute_path = File.join(dir, path)
        directory     = File.directory?(absolute_path)
        next [] if File.symlink?(absolute_path) || excluded?(path, directory)
        next listed_files(absolute_path) if directory

        File.file?(absolute_path) && ImmosquareCleaner.supported?(absolute_path) ? [absolute_path] : []
      end
    end

    ##============================================================##
    ## --cached lists deleted-but-uncommitted files as well:
    ## File.file? filters them out afterwards. The glob fallback
    ## keeps files only, a listed directory being walked again
    ##============================================================##
    def relative_paths(dir)
      output, status = git_ls_files(dir)
      return output.split("\0").uniq if status&.success?

      Dir.glob("**/*", :base => dir).reject {|path| File.directory?(File.join(dir, path)) }
    end

    def git_ls_files(dir)
      Open3.capture2("git", "-C", dir, "ls-files", "-z", "--cached", "--others", "--exclude-standard", :err => File::NULL)
    rescue Errno::ENOENT
      nil
    end

    def excluded?(path, directory)
      segments = path.split("/")
      folders  = directory ? segments : segments[0..-2]
      return true if folders.intersect?(EXCLUDED_DIRS) || "#{path}/".start_with?(*EXCLUDED_PATHS.map {|excluded| "#{excluded}/" })
      return true if self.class.generator_template?(folders)

      !directory && (EXCLUDED_FILES.include?(segments.last) || segments.last.end_with?(*EXCLUDED_SUFFIXES))
    end

  end
end
